//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiseaseDetection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseTSCR
    {
        public int Id { get; set; }
        public string DiseaseName { get; set; }
        public string Types { get; set; }
        public string Symptoms { get; set; }
        public string Causes { get; set; }
        public string Remedies { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
